"""empty message

Revision ID: 05103962b4c5
Revises: f0f82e3db54c
Create Date: 2024-12-04 11:49:55.944225

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05103962b4c5"
down_revision = "f0f82e3db54c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
