"""empty message

Revision ID: 2cf6b6c1eae5
Revises: 05103962b4c5
Create Date: 2024-12-04 13:50:28.220431

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cf6b6c1eae5"
down_revision = "05103962b4c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_email")
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.drop_index("ix_user_username")
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.create_index("ix_user_username", ["username"], unique=False)
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_index("ix_user_email", ["email"], unique=False)

    # ### end Alembic commands ###
